def fun():
   x=8
print(x)

fun()
print(x) #error will be shown
